version: '3'
services:
    openflorian-ui:
         build: .
         container_name: openflorian-ui
         environment:
             API_BASE_URL: http://localhost:8080
         restart: on-failure
         expose:
             - '8080'
         ports:
             - '8081:8080'
