exports.OPENWEATHER_CONDITONS = {
    0: "wi-na",

    200: "wi-thunderstorm",
    201: "wi-thunderstorm",
    202: "wi-thunderstorm",
    210: "wi-thunderstorm",
    211: "wi-thunderstorm",
    212: "wi-thunderstorm",
    221: "wi-thunderstorm",
    230: "wi-thunderstorm",
    231: "wi-thunderstorm",
    232: "wi-thunderstorm",

    300: "wi-rain-mix",
    301: "wi-rain-mix",
    302: "wi-rain-mix",
    310: "wi-rain-mix",
    311: "wi-rain-mix",
    312: "wi-rain-mix",
    321: "wi-rain-mix",

    600: "wi-snow",
    601: "wi-snow",
    602: "wi-strong-wind wi-snow",
    621: "wi-snow",
    611: "wi-sleet",

    701: "wi-dust",
    711: "wi-smog",
    721: "wi-dust",
    731: "wi-dust",
    741: "wi-dust",

    500: "wi-showers",
    501: "wi-showers",
    502: "wi-storm-showers",
    503: "wi-storm-showers",
    504: "wi-storm-showers",
    511: "wi-snow",
    520: "wi-showers",
    521: "wi-showers",
    522: "wi-storm-showers",

    800: "wi-day-sunny",
    801: "wi-cloud",
    802: "wi-cloudy",
    803: "wi-cloudy",
    804: "wi-cloudy",

    900: "wi-tornado",
    901: "wi-hurricane",
    902: "wi-hurricane",
    903: "wi-snowflake-cold",
    904: "wi-thermometer",
    905: "wi-strong-wind",
    906: "wi-hail"
}

exports.YAHOOWEATHER_CONDITIONS = {
    0: "wi-tornado",
    1: "wi-hurricane",
    2: "wi-hurricane",
    3: "wi-thunderstorm",
    4: "wi-thunderstorm",
    5: "wi-sleet",
    6: "wi-sleet",
    7: "wi-sleet",
    8: "wi-sleet",
    9: "wi-sleet wi-snowflake-cold",
    10: "wi-showers wi-snowflake-cold",
    11: "wi-showers",
    12: "wi-showers",
    13: "wi-strong-wind wi-snow",
    14: "wi-snow",
    15: "wi-strong-wind wi-snow",
    16: "wi-snow",
    17: "wi-hail",
    18: "wi-sleet",
    19: "wi-dust",
    20: "wi-dust",
    21: "wi-dust",
    22: "wi-smog",
    23: "wi-cloudy-gusts",
    24: "wi-strong-wind",
    25: "wi-snowflake-cold",
    26: "wi-cloudy",
    27: "wi-night-alt-cloudy",
    28: "wi-day-cloudy",
    29: "wi-night-alt-cloudy",
    30: "wi-day-cloudy",
    31: "wi-stars",
    32: "wi-day-sunny",
    33: "wi-night-clear",
    34: "wi-day-sunny",
    35: "wi-hail",
    36: "wi-thermometer",
    37: "wi-storm-showers",
    38: "wi-storm-showers",
    39: "wi-storm-showers",
    40: "wi-showers",
    41: "wi-snow-wind",
    42: "wi-snow",
    43: "wi-snow",
    44: "wi-cloudy",
    45: "wi-storm-showers",
    46: "wi-snow",
    47: "wi-storm-showers",
}